HTMX_MVC/Models/ErrorViewModel.cs
namespace HTMX_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HTMX_MVC/Models/FormModel.cs
namespace HTMX_MVC.Models
{
    public class FormModel
    {
        public string Name { get; set; } = "";
        public string NameError { get; set; } = "";
        public string Email { get; set; } = "";
        public string EmailError { get; set; } = "";
        public string Password { get; set; } = "";
        public string PasswordError { get; set; } = "";
        public bool HasAgreedToTerms { get; set; } = false;
        public string HasAgreedToTermsError { get; set; } = "";

        public bool loading { get; set; } = false;
    }
}

HTMX_MVC/Models/SearchModel.cs
namespace HTMX_MVC.Models
{
    public class SearchModel
    {
        public string SearchQuery { get; set; }
    }
}

HTMX_MVC/Controllers/FormController.cs
using HTMX_MVC.businessLogic;
using HTMX_MVC.Controllers.ControllerUtils;
using HTMX_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace HTMX_MVC.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Index()
        {
            var model = HttpContext.GetCreateModel<FormModel>();
            return View(model);
        }

        [HttpPost]
        public IActionResult ContactForm()
        {
            var model = HttpContext.GetCreateModel<FormModel>();

            model.NameError = NameValidation.ValidateName(model.Name);
            model.EmailError = EmailValidation.ValidateEmail(model.Email);
            model.PasswordError = PasswordValidation.ValidatePassword(model.Password);
            model.HasAgreedToTermsError = TermsValidationcs.ValidateTerms(model.HasAgreedToTerms);

            if (
                string.IsNullOrEmpty(model.NameError)
                &&
                string.IsNullOrEmpty(model.EmailError)
                &&
                string.IsNullOrEmpty(model.PasswordError)
                &&
                string.IsNullOrEmpty(model.HasAgreedToTermsError)
            )
            {
                Response.Headers.Add("HX-Redirect", "SlowPage");
                Thread.Sleep(5000);
            };

            HttpContext.SaveModel(model);
            return PartialView(model);
        }

        [HttpPut]
        public IActionResult InputName(string name)
        {
            var model = HttpContext.GetCreateModel<FormModel>();
            model.Name = name ?? string.Empty;
            model.NameError = NameValidation.ValidateName(model.Name);

            HttpContext.SaveModel(model);
            return PartialView(model);
        }

        [HttpPut]
        public IActionResult InputEmail(string email)
        {
            var model = HttpContext.GetCreateModel<FormModel>();
            model.Email = email ?? string.Empty;
            model.EmailError = EmailValidation.ValidateEmail(model.Email);
            HttpContext.SaveModel(model);

            return PartialView(model);
        }

        [HttpPut]
        public IActionResult InputPassword(string password)
        {
            var model = HttpContext.GetCreateModel<FormModel>();
            model.Password = password ?? string.Empty;
            model.PasswordError = PasswordValidation.ValidatePassword(model.Password);
            HttpContext.SaveModel(model);

            return PartialView(model);
        }

        [HttpPut]
        public IActionResult InputTerms(string acceptedTerms)
        {
            var model = HttpContext.GetCreateModel<FormModel>();

            model.HasAgreedToTerms = acceptedTerms == "on";
            model.HasAgreedToTermsError = TermsValidationcs.ValidateTerms(model.HasAgreedToTerms);
            HttpContext.SaveModel(model);

            return PartialView(model);
        }
    }
}

HTMX_MVC/Controllers/SearchController.cs
using HTMX_MVC.Controllers.ControllerUtils;
using HTMX_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace HTMX_MVC.Controllers
{
    public class SearchController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var model = HttpContext.GetCreateModel<SearchModel>();
            return View(model);
        }

        [HttpGet]
        public IActionResult Search(string searchQuery)
        {
            var model = HttpContext.GetCreateModel<SearchModel>();
            model.SearchQuery = searchQuery ?? string.Empty; ;

            HttpContext.SaveModel(model);
            return PartialView(model);
        }
    }
}

HTMX_MVC/Views/Form/ContactForm.cshtml
@model FormModel

<div id="spinner" style="display:none;">
    <div class="w-100 mt-5 d-flex justify-content-center align-items-center">
        <div class="spinner"></div>
    </div>
</div>

<form id="contact-form">
        @Html.Partial("~/Views/Form/InputName.cshtml", Model)
        @Html.Partial("~/Views/Form/InputEmail.cshtml", Model)
        @Html.Partial("~/Views/Form/InputPassword.cshtml", Model)
        @Html.Partial("~/Views/Form/InputTerms.cshtml", Model)

        <button type="button"
                class="btn btn-primary"
                hx-post="@Url.Action("ContactForm")"
                hx-trigger="click"
                hx-target="#contact-form"
                hx-swap="outerHTML"
                hx-indicator="#spinner"
        >
            Submit
        </button>
</form>

HTMX_MVC/Views/Form/Index.cshtml
@model FormModel

<div class="col-12 col-md-6 mx-auto">
    <h2>Create an Account Example</h2>
    @Html.Partial("~/Views/Form/ContactForm.cshtml", Model)
</div>

HTMX_MVC/Views/Form/InputEmail.cshtml
@model FormModel
@{
    var showErrors = !String.IsNullOrEmpty(Model.EmailError);
}

<div class="form-group my-3" id="input-email">
    <label for="email">Email address</label>
    <input 
        name="email"
        type="email"
        class="form-control @(showErrors ? "error" : "")"
        id="email"
        placeholder="Enter email"
        hx-put="@Url.Action("InputEmail")"
        hx-trigger="blur"
        hx-target="#input-email"
        hx-swap="outerHTML"
        value="@Model.Email"
    >
    @if(showErrors)
    {
        <div class="error mt-1 error">
            @Model.EmailError
        </div>
    }
    
</div>

HTMX_MVC/Views/Form/InputName.cshtml
@model FormModel
@{
    var showErrors = !String.IsNullOrEmpty(Model.NameError);
}

<div class="form-group my-3" id="inputName">
    <label for="name">Name</label>
    <input 
        name="name"
        type="text"
        class="form-control @(showErrors ? "error" : "")"
        id="name"
        placeholder="Enter name"
        hx-put="@Url.Action("InputName")"
        hx-trigger="blur"
        hx-target="#inputName"
        hx-swap="outerHTML"
        value="@Model.Name"
    >
    @if (showErrors)
    {
        <div class="error mt-1 error">
            @Model.NameError
        </div>
    }
</div>

HTMX_MVC/Views/Form/InputPassword.cshtml
@model FormModel
@{
    var showErrors = !String.IsNullOrEmpty(Model.PasswordError);
}

<div class="form-group my-3" id="inputPassword">
    <label for="password">Password</label>
    <input 
        name="password" 
        type="password"
        class="form-control @(showErrors ? "error" : "")"
        id="password"
        placeholder="Enter password"
        hx-put="@Url.Action("InputPassword")"
        hx-trigger="blur"
        hx-target="#inputPassword"
        hx-swap="outerHTML"
        value="@Model.Password"
    >
    @if(showErrors)
    {
        <div class="error mt-1 error">
            @Model.PasswordError    
        </div>
    }
</div>

HTMX_MVC/Views/Form/InputTerms.cshtml
@model FormModel

@{
    var showErrors = !String.IsNullOrEmpty(Model.HasAgreedToTermsError);
}


<div class="form-group form-check my-3" id="input-terms">
    <input type="checkbox"
           name="acceptedTerms"
           class="form-check-input cursor-pointer"
           hx-put="@Url.Action("InputTerms")"
           hx-trigger="click blur"
           hx-target="#input-terms"
           hx-swap="outerHTML"
           value="@Model.HasAgreedToTerms"
           checked="@Model.HasAgreedToTerms"
           id="terms">
    <label class="form-check-label cursor-pointer"
           for="terms">
        Accept Terms and Conditions
    </label>
    @if (showErrors)
    {
        <div class="error mt-1" style="margin-left: -1.5rem">
            @Model.HasAgreedToTermsError
        </div>
    }
    
</div>

HTMX_MVC/Views/Search/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    ViewData["Title"] = "Home Page";
}
<div class="col-12 col-md-6 mx-auto">
<div class="text-center">
    <input 
        class="form-control" 
        type="search"
        name="searchQuery" 
        placeholder="Begin Typing To Search Users..."
        hx-get="@Url.Action("Search")"
        hx-trigger="input changed delay:1ms, search"
        hx-target="#search-results"
        hx-indicator=".htmx-indicator"
    >

    <div 
        id="loadingIndicator" 
        style="display: none;"
    > Loading...
    </div>
    <ul id="search-results"
        class="list-group mt-3"
    >
    </ul>
</div>
</div>

HTMX_MVC/Views/Search/Search.cshtml
@model SearchModel
@using HTMX_MVC.Data

@{
    var searchQuery = Model.SearchQuery.ToLower();

    var files = HTMX_MVC.Data.Filenames.GetFilenames();

    IEnumerable<FileInfo> fileMatches = 
        files.Where(file =>
            file.Activity.ToLower().Contains(searchQuery)
            ||
            file.Area.ToLower().Contains(searchQuery)
    );
}

<div class="list-group">
    @foreach (var file in fileMatches)
    {
        <a 
            href="#" 
            class="list-group-item list-group-item-action"
        >
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">@file.Activity</h5>
                <small>@file.Area</small>
            </div>
        </a>
    }
</div>

HTMX_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HTMX_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HTMX_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Search" asp-action="Index">HTMX_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="Index">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HTMX_MVC - <a asp-area="" asp-controller="Search" asp-action="Index">Search</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/htmx.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HTMX_MVC/Views/SlowPage/Index.cshtml
@{
    ViewData["Title"] = "SlowPage";
}

<h1>SlowPage</h1>